-- 코드를 입력하세요
SELECT CP.CART_ID, (CASE 
    WHEN SUM(CP.PRICE) > C.MINIMUM_REQUIREMENT THEN 0 
    ELSE 1 END) as ABUSED
FROM CART_PRODUCTS as CP, COUPONS as C
WHERE CP.CART_ID = C.CART_ID
GROUP BY CP.CART_ID;